apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "python-cronjob.fullname" . }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.job.restartPolicy }}
          containers:
            - name: python-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
{{ toYaml .Values.command | indent 16 }}
              args:
{{ toYaml .Values.args | indent 16 }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
