image:
  repository: registry.kroup.xyz/scraper
  tag: latest
  pullPolicy: Always

cronjob:
  # every hour at minute 0
  schedule: "0 */2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

job:
  restartPolicy: Never
  # don't retry on failure (prevents "run another" retry pod)
  backoffLimit: 0
  # optional safety limit: kill job if it runs too long
  # activeDeadlineSeconds: 3600

command:
  - python
args:
  - -m
  - scraper.main

resources: {}
